### ISSUE TITLE
Create  Cards  and  Add Information 

### ISSUE THREAD

**Issue by naishg** [info442-aut21/d-team#18]
Using HTML and CSS and incorporating flexbox, create 3 different cards. Each card should correspond to the number of stops. The card on the far left should say '1 Stop' followed by the middle one which states '2 Stops' and then '3 or more Stops'.

This issue completes requirement C.1

**Comment by IamSuperB4** [comment]
Still need to add proper pictures to the choose number of activity cards. Reopening issue
