### ISSUE TITLE
Create cards for activity Plan 

### ISSUE THREAD

**Issue by naishg** [info442-aut21/d-team#33]
Using HTML and CSS create cards based on the number of activity stops selected from the choose number of activities page. (For example if chose 2 activities, page will only display 2 final card with activity plan). 

In total should create 3 sets of card displays: 1, 2 and 3. 

This issue completes requirement E.1

**Comment by IamSuperB4** [comment]
Still need to add proper pictures to the number of activities cards. Reopening issue
