### ISSUE TITLE
[Minor] "Your Adventure Awaits" does indicate when the loading is complete

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/d-team#66]
Description: Even after the page is loaded (the adventure is created), "Your Adventure Awaits" is still displayed it doesn't take me to the next page
Expected: I was waiting for the adventure to be displayed once the loading is completed
Actual: I have to scroll down to see the results which lead to confusion of whether or not a page is loaded
Tested on Chrome Version 96.0.4664.55 (Official Build) on MacOs Catalina.

**Comment by IamSuperB4** [comment]
Cannot reproduce. Feels like a one-time issue. Scrolling works every time for us

**Comment by IamSuperB4** [comment]
#77 is a duplicate
