### ISSUE TITLE
[minor] mobile view of home page is not responsive

### ISSUE THREAD

**Issue by njkpark** [info442-aut21/d-team#67]
Mobile view of homepage is not responsive, but still understandable and generally looks correct. Layout is not mobile friendly (only homepage).

Environment: apple iphone 12 on chrome/safari

Steps: clicking link to website through mobile phone

Expected result: the homescreen should have fit on mobile window size - not having to scroll side to side to see content

actual result: the homepage text is not centered, the image does not fit on the mobile screen properly

**Comment by IamSuperB4** [comment]
This will take a long time to fully fix and test. There are other higher priorities for us. This will be a stretch goal.

**Comment by IamSuperB4** [comment]
Reassigned to issues #90-#96
