### ISSUE TITLE
[Minor] Label icon at the top right of the adventure options

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/d-team#68]
The arrow icon at the top right of the options for the directions is not specified on what action was supposed to happen. 

Environment: Google Chrome  96.0.4664.55 and Mac OS Big Sur

Steps to reproduce: Icon title/Description "Shuffle" Link
1. go through the adventure steps
2. receive recommended adventures
3. View recommended adventures
Expected: "Click to Shuffle"
Actual: An arrows icon

**Comment by IamSuperB4** [comment]
We can try find a better emoji than the shuffle emoji

**Comment by cherimarie** [comment]
I'd also recommend adding a `title` attribute to the button element so that a tool tip appears on hover (https://www.dofactory.com/html/button/title).
