### ISSUE TITLE
[Minor] Shuffle button changes the order of the card you clicked on

### ISSUE THREAD

**Issue by sershon** [info442-aut21/d-team#69]
When clicking the small shuffle icon in the top right of the activity card after completing the quiz section, it moves the chard you clicked on above the others, making it look like two of the activities changed. I would expect that the shuffle button would just change the activity and not the order of the cards. I'm not sure if the intended use of the shuffle button is to change the order of the cards, or change the activity itself. It seems to me like one of these is unintended.
Encountered on MacOS Monterey and Chrome Version 95.0.4638.69 (Official Build) (arm64)

**Comment by IamSuperB4** [comment]
I knew about this, and I didn't find it to be worth the time to place the replacement div correctly in the list. It isn't a priority for us, but if we have time we can make it a stretch goal.

**Comment by IamSuperB4** [comment]
I may very well fix this issue, but I don't feel comfortable committing to it until everything else is fixed and I do more research on how to place divs between before/after other divs.
