### ISSUE TITLE
[Minor] On Here is your Adventure, some of suggestions name and contact info are not alligned with the others

### ISSUE THREAD

**Issue by Skylitmoon** [info442-aut21/d-team#70]
Tested on MacOS Monterey and Google Chrome Version 96.0.4664.45. When viewing the suggestion cards, some of the titles and contact info do not align. It would be easier to read and more consistent if all cards information was align the same way.

**Comment by IamSuperB4** [comment]
With the way that the flexbox works and the "justify-content: space-between" does spacing, this was a problem I knew about and could not fix. We can try centering the text in the cards and see if it looks better, but we won't make this issue a priority.

**Comment by IamSuperB4** [comment]
Centering the text solved that issue
