### ISSUE TITLE
[Minor] Links do not open in new tab 

### ISSUE THREAD

**Issue by nsnatthapat** [info442-aut21/d-team#71]
Summary: Clicking on team linkedIn profiles does not open links in a new tab

Environment: Version 95.0.4638.69 (Official Build) (x86_64) on MacOS Monterey

Steps to Reproduce: 
1. Navigate to About Us from NavBar
2. Click on a team member linkedin profile

Expected Result: Opens up linkedin in new tab
Actual: Navigates to linkedin

**Comment by IamSuperB4** [comment]
You can right-click and open the link in a new tab, that is how most website links work.

**Comment by cherimarie** [comment]
Whether to have links in a new tab or not is a design decision. Just a note that to have that behavior, it's just necessary to add `target="blank"` attribute to the anchor tag element.
