### ISSUE TITLE
[minor] ‘create adventure’ images not mobile-friendly and navbar overlaps other text when scrolling down

### ISSUE THREAD

**Issue by njkpark** [info442-aut21/d-team#72]
Pictures of the map are stretched too thin. Additionally, the navbar is stagnant text which overlaps the texts of the question when scrolling down.

Environment: Apple iphone 12 on chrome/safari

Steps to reproduce: click on link to website on mobile device, click on “create adventure” on homepage, scroll up and down to see navbar issue and images

expected result: images are more mobile friendly and responsive. Other text on the website does not interfere with the navbar

actual result: images are very thin and the texts overlap when scrolling

![2D198079-2CD2-46DA-8F8C-5DF64C5E21CF](https://user-images.githubusercontent.com/62912422/142906064-e4e902f4-734f-410e-95fd-b9cf04233133.png)

**Comment by IamSuperB4** [comment]
We knew about this but will be pretty complex to fix. It was and still is a stretch goal. If we did fix this, we would prioritize the worst-looking parts, like choosing a mood.

**Comment by IamSuperB4** [comment]
Reassigned to issues #90-#96

**Comment by IamSuperB4** [comment]
#80 is a duplicate

**Comment by cherimarie** [comment]
@IamSuperB4  I think this could be fixed fairly easily using flexbox.
