### ISSUE TITLE
[Minor/Enhancement] Navbar is not consistent across all of the pages

### ISSUE THREAD

**Issue by sershon** [info442-aut21/d-team#73]
On the landing page, the two options on the navbar are directory, and about us, on the homepage it is home and about us, and on the about us page it is home and directory. This is a bit disorienting and I can't tell if it is intended or not. I believe it would give users a better sense of direction if all three links appeared on the navbar at all times.

**Comment by IamSuperB4** [comment]
Yes, we can fix this.

**Comment by IamSuperB4** [comment]
Each page has different navbar buttons and in different orders, we will make them consistent throughout each page.

**Comment by IamSuperB4** [comment]
#81 is a duplicate
