### ISSUE TITLE
[Enhancement] search bar on directory page might be helpful, as well as styling directory page to match the rest of the site

### ISSUE THREAD

**Issue by swaleha6** [info442-aut21/d-team#75]
- [Enhancement] search bar on directory page might be helpful, as well as styling directory page to match the rest of the site
- Firefox on Windows 10
- clicked directory button on navbar
- search bar could be useful here

**Comment by IamSuperB4** [comment]
This is a good thought. But we do not feel this is a priority. What we would like to do is put is the businesses in alphabetical order to make searching for a business easier. We will do this if MongoDB has an easy way to SORT BY like in SQL, we will do that.

**Comment by IamSuperB4** [comment]
Doing #89 instead, which partially meets this requirement and is done in the same spirit.

**Comment by IamSuperB4** [comment]
#84 is a duplicate
