### ISSUE TITLE
[ Minor ] on mobile - the homepage spills over so you have to slide to see full homepage

### ISSUE THREAD

**Issue by angelinapoltavskiy** [info442-aut21/d-team#76]
When I opened the app on my phone the home page isn't entirely seen, you have to slide to see the entire thing
environment: safari browzer, iphone XR
steps to reproduce: on a mobile device of iphone XR or smaller screen, open up you application - directly on the homepage you should see the issue
expected result: the entire homepage would be visible at first glance
actual result: you have to slide back and forth to see the entirety of the homepage on mobile

**Comment by IamSuperB4** [comment]
We knew this is an issue, we can kind of dump this into "mobile responsiveness". If we have time, we will fix this, but no guarantee.

**Comment by IamSuperB4** [comment]
Reassigned to issues #90-#96
