### ISSUE TITLE
[Minor] Nav Bar Labels Overlap with Text and Images on the Page (hard to read)

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/d-team#79]
Most prominently on mobile, when scrolling down to select options for creating our adventure, the navigation bar items start to overlap with the text and images on the page due to its transparent background, making it difficult to read if the user wants to navigate back to a page.

Environment: Windows 11 - Brave Browser: Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

To reproduce this issue or look into this enhancement, you can click "Create Adventure" on the opening page and size the width of the window down as much as possible. Scroll down the page and you'll start seeing the text from the nav bar start to overlap with images and text from the page.

Perhaps you can consider either making the navbar menu have a solid color background so that it can be consistently readable as you scroll down the page, or have it not fixed on the page as you scroll down. The results I was expected would be either of the two suggestions I have provided.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/72470963/142907919-9ef67e66-da6e-492b-8232-3e612c2327f3.png">

**Comment by IamSuperB4** [comment]
This is something we will fix. The navbar needs to be a solid color, not transparent, at least on every page except the landing page. We will work with our designer @manyaj57 on how to go about this.

**Comment by IamSuperB4** [comment]
#82 is a duplicate
