### ISSUE TITLE
[Minor] Judy Nguyen LinkedIn button goes returns user to the top of the page

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/d-team#85]
There isn't an external link to the LinkedIn button for Judy Nguyen like there is for the other members of the group. As a personal preference, I would suggest that these redirects be opened in a new tab rather than the current tab so users can navigate back to the page easily while being able to do separate interactions on LinkedIn and not having to hit the back button a ton of times to get back to your web app.

Environment: Windows 11 - Brave Browser: Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

To reproduce this issue:
Home page > About us > Scroll down and clicked the "LinkedIn" button for Judy Nguyen

The expected result is that the user would be redirected to Judy Nguyen's LinkedIn profile.

The actual result is that the user is returned to the top of the current page when the button is selected.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/72470963/143050455-c3117927-90f2-4fcc-b26c-51757aef07e9.png">

**Comment by judysdesign** [comment]
I will fix this soon.
