### ISSUE TITLE
[Feature Request] Users MUST select x number of options depending on how many stops they want to make

### ISSUE THREAD

**Issue by aramos10-1863966** [info442-aut21/d-team#86]
Description: When I was creating an adventure, I wanted to test if the adventure creator would give me 2 stops of the same type. However, it required that I select 2 options of different types. Some users on the site may want to explore multiple shopping venues around the area or multiple restaurants. Thus, insisting on selecting multiple options feels restricting.

Expectation: Create adventures with multiple stops of the same type

Environment: Microsoft Edge Version 96.0.1054.29

**Comment by IamSuperB4** [comment]
We thought about this, but we made the design decision to do this since it made the adventure logic much more complex. We won't fix this
