### ISSUE TITLE
[Enhancement] Add a Google Map route connecting the selected stops on the adventure

### ISSUE THREAD

**Issue by jovecalimlim** [info442-aut21/d-team#87]
Description: After creating a user's adventure, show a Google Map that shows all the stops that we're shown for the user and a route between them all.

Explanation: Similar to the Wanderlog app (see attached screenshot), this would add to the user experience and show them how close each stop is to each other and a possible route that the user can take between each one.

<img width="1139" alt="Screen Shot 2021-11-23 at 8 35 51 PM" src="https://user-images.githubusercontent.com/56002881/143187316-4e82f886-ac02-494f-bb55-648ed3d0bb2e.png">

**Comment by IamSuperB4** [comment]
This may or may not be a complex problem to solve. We are not using the Google Maps API, I don't know if you can do this through a URL alone. This is not something we will do
