### ISSUE TITLE
[Enhancement] Add a consistent color theme to all pages

### ISSUE THREAD

**Issue by jovecalimlim** [info442-aut21/d-team#88]
Description: Have one color scheme across all site pages.

Explanation: Switching from the About page, to the Directory page, to the Create Adventure page, each seems to have a different color scheme between the background color and header color which can seem a bit disjointed when switching pages. Choosing a singular color scheme could make site navigation feel more seamless.

**Comment by IamSuperB4** [comment]
This is something our designer can work on
